language: scala
scala:
- 2.11.2
script:
- sbt clean coverage test coverageReport
after_success:
- sbt coveralls
deploy:
  provider: heroku
  api_key:
    secure: dxHe13761bVfWbH+010KHNayTAPtQ+dmS1ka4FXux51N/fbK55k/R4lrMLfahlqiH9xfHkWvyNsgUfkF1nmTSb9e2xfYDeH2nIiOXVAbIHrGh5pS2+o+781rEKQCkvk5AKP03ZuQnMBrNp4CeXpzzqYz03M7noAcAnYsTjOvXD+LPJlSgCoZdzpexrKBFo1mNBFWosS3AyzPPMNG4j7UBDsYC9m040BwaUJjgv2C/ojZFfBLx5md1tIvq+99PAx9XVsjja4g3erfDQ8OjpQ4QLXngpdhB791OxplakMICXotDxI4j2k7N1zfMM/qhYYjTXbJsJLk4SSnhWS6FaZQm29eWnaXaEbQKqlZvhQKJyIk4QAEyM88Q6TBM4SItSqUjo4tl9DaXEW5tFpAeHBAHwVGvyRFTled7wBPBt535zEq7taT0i2CxmHZyAGVm5aoU+ga81D02vNSBkxJpqNiSiFhEX8iqJIZq2gPnoOumQFgK1HeiVg9QxWzt3Svwye32/425CNTXAQ6Urs8HPX9cZA2SQC2gpSCuj8OuHV4orV8i4gzXPveMf3W8fNvstiX8B/WfC0t/SIYEQ5o+TFvGPsTU4YA879kPf2ATSQcLmg/f9t0EKcfC0np0o3TiMWk3NKPcSHVCO4U5l97eYqrMfpIP1TysdTBIbh8OUgqjtA=
